apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: phoenix-app
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/codesentia/phoenix-app
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: 'phoenix-{{path.basename}}'
      labels:
        team: phoenix
    spec:
      project: team-phoenix
      source:
        repoURL: https://github.com/codesentia/phoenix-app
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: team-phoenix
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
